version: '2'

services:
  mongo:
    restart: always
    image: mongo:3.4
    expose:
      - "27017"
    ports:
      - "27001:27017"
    volumes:
      - mongo:/data/db
    mem_limit: 96m
  
  # mariadb:
  #   restart: always
  #   image: mariadb:10.3
  #   expose:
  #     - "3306"
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   mem_limit: 96m
  #   env_file:
  #       - docker/variables.env

  app:
    image: akkapong/php-nginx-phalcon-mongo:latest
    restart: always
    ports:
      - "8001:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx-sites:/etc/nginx/sites-available
      - ./docker/nginx-sites:/etc/nginx/sites-enabled
    mem_limit: 128m
    depends_on:
      # - mariadb
      - mongo
    links:
      - mongo
      # - mariadb
  app-swagger-ui:
    image: swaggerapi/swagger-ui
    restart: always
    ports:
      - "81:8080"
    volumes:
      - .:/app
    mem_limit: 96m
    environment:
        - SWAGGER_JSON=/app/swagger.json

volumes:
  mongo:
    driver: local
  mysql:
    driver: local